/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_MyActivity */

#ifndef _Included_com_example_MyActivity
#define _Included_com_example_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_MyActivity
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_MyActivity_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
