/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blogspot_jia3ep_test_HistogramView */

#ifndef _Included_com_blogspot_jia3ep_test_HistogramView
#define _Included_com_blogspot_jia3ep_test_HistogramView
#ifdef __cplusplus
extern "C" {
#endif
#undef com_blogspot_jia3ep_test_HistogramView_NO_ID
#define com_blogspot_jia3ep_test_HistogramView_NO_ID -1L
#undef com_blogspot_jia3ep_test_HistogramView_VISIBLE
#define com_blogspot_jia3ep_test_HistogramView_VISIBLE 0L
#undef com_blogspot_jia3ep_test_HistogramView_INVISIBLE
#define com_blogspot_jia3ep_test_HistogramView_INVISIBLE 4L
#undef com_blogspot_jia3ep_test_HistogramView_GONE
#define com_blogspot_jia3ep_test_HistogramView_GONE 8L
#undef com_blogspot_jia3ep_test_HistogramView_DRAWING_CACHE_QUALITY_LOW
#define com_blogspot_jia3ep_test_HistogramView_DRAWING_CACHE_QUALITY_LOW 524288L
#undef com_blogspot_jia3ep_test_HistogramView_DRAWING_CACHE_QUALITY_HIGH
#define com_blogspot_jia3ep_test_HistogramView_DRAWING_CACHE_QUALITY_HIGH 1048576L
#undef com_blogspot_jia3ep_test_HistogramView_DRAWING_CACHE_QUALITY_AUTO
#define com_blogspot_jia3ep_test_HistogramView_DRAWING_CACHE_QUALITY_AUTO 0L
#undef com_blogspot_jia3ep_test_HistogramView_SCROLLBARS_INSIDE_OVERLAY
#define com_blogspot_jia3ep_test_HistogramView_SCROLLBARS_INSIDE_OVERLAY 0L
#undef com_blogspot_jia3ep_test_HistogramView_SCROLLBARS_INSIDE_INSET
#define com_blogspot_jia3ep_test_HistogramView_SCROLLBARS_INSIDE_INSET 16777216L
#undef com_blogspot_jia3ep_test_HistogramView_SCROLLBARS_OUTSIDE_OVERLAY
#define com_blogspot_jia3ep_test_HistogramView_SCROLLBARS_OUTSIDE_OVERLAY 33554432L
#undef com_blogspot_jia3ep_test_HistogramView_SCROLLBARS_OUTSIDE_INSET
#define com_blogspot_jia3ep_test_HistogramView_SCROLLBARS_OUTSIDE_INSET 50331648L
#undef com_blogspot_jia3ep_test_HistogramView_KEEP_SCREEN_ON
#define com_blogspot_jia3ep_test_HistogramView_KEEP_SCREEN_ON 67108864L
#undef com_blogspot_jia3ep_test_HistogramView_SOUND_EFFECTS_ENABLED
#define com_blogspot_jia3ep_test_HistogramView_SOUND_EFFECTS_ENABLED 134217728L
#undef com_blogspot_jia3ep_test_HistogramView_HAPTIC_FEEDBACK_ENABLED
#define com_blogspot_jia3ep_test_HistogramView_HAPTIC_FEEDBACK_ENABLED 268435456L
#undef com_blogspot_jia3ep_test_HistogramView_FOCUSABLES_ALL
#define com_blogspot_jia3ep_test_HistogramView_FOCUSABLES_ALL 0L
#undef com_blogspot_jia3ep_test_HistogramView_FOCUSABLES_TOUCH_MODE
#define com_blogspot_jia3ep_test_HistogramView_FOCUSABLES_TOUCH_MODE 1L
#undef com_blogspot_jia3ep_test_HistogramView_FOCUS_BACKWARD
#define com_blogspot_jia3ep_test_HistogramView_FOCUS_BACKWARD 1L
#undef com_blogspot_jia3ep_test_HistogramView_FOCUS_FORWARD
#define com_blogspot_jia3ep_test_HistogramView_FOCUS_FORWARD 2L
#undef com_blogspot_jia3ep_test_HistogramView_FOCUS_LEFT
#define com_blogspot_jia3ep_test_HistogramView_FOCUS_LEFT 17L
#undef com_blogspot_jia3ep_test_HistogramView_FOCUS_UP
#define com_blogspot_jia3ep_test_HistogramView_FOCUS_UP 33L
#undef com_blogspot_jia3ep_test_HistogramView_FOCUS_RIGHT
#define com_blogspot_jia3ep_test_HistogramView_FOCUS_RIGHT 66L
#undef com_blogspot_jia3ep_test_HistogramView_FOCUS_DOWN
#define com_blogspot_jia3ep_test_HistogramView_FOCUS_DOWN 130L
/*
 * Class:     com_blogspot_jia3ep_test_HistogramView
 * Method:    decodeYUV420SP
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_blogspot_jia3ep_test_HistogramView_decodeYUV420SP
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_blogspot_jia3ep_test_HistogramView
 * Method:    calculateHistogram
 * Signature: (J[I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_blogspot_jia3ep_test_HistogramView_calculateHistogram
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jintArray);

/*
 * Class:     com_blogspot_jia3ep_test_HistogramView
 * Method:    doneCppSide
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_blogspot_jia3ep_test_HistogramView_doneCppSide
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blogspot_jia3ep_test_HistogramView
 * Method:    initCppSide
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_blogspot_jia3ep_test_HistogramView_initCppSide
  (JNIEnv *, jobject);

/*
 * Class:     com_blogspot_jia3ep_test_HistogramView
 * Method:    getMaxHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_blogspot_jia3ep_test_HistogramView_getMaxHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blogspot_jia3ep_test_HistogramView
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_blogspot_jia3ep_test_HistogramView_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blogspot_jia3ep_test_HistogramView
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_blogspot_jia3ep_test_HistogramView_getWidth
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
